version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    container_name: backend_michael
    ports:
      - '8090:80'
    command: bash -c "cd backend; python start_db.py; python /backend/backend/scripts/ETL.py; uvicorn main:app --host 0.0.0.0 --port 80;"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/backend/backend
    depends_on:
      - db
  frontend:
    build: .
    container_name: frontend_BLOODY_VLADI
    ports:
      - '3000:3000'
    command: bash -c "cd frontend; cd for_vlad; npm run start"
volumes:
  app_data:


