version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: backend
      dockerfile: ./backend.Dockerfile
    container_name: backend_michael
    ports:
      - '8090:80'
    command: bash -c "cd /backend; python start_db.py; python /backend/scripts/ETL.py; uvicorn main:app --host 0.0.0.0 --port 80;"
    stdin_open: true # -i
    tty: true # -t
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    environment:
      - PYTHONPATH=/backend
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: frontend_BLOODY_VLADI
    ports:
      - '3000:3000'
    entrypoint: ["bash", "-c", "cd /frontend; npm install ; npm run build ; npm run start"]
    volumes:
      - ./frontend/for_vlad:/frontend

volumes:
  pgdata:
  backend:
  frontend: